/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.venda;

import emissorsat.DLL;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.Currency;
import java.util.HashMap;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import jpkj.Bd;
//import jpkj.List;
import jpkj.Log;
import jpkj.Msg;
import jpkj.Util;
import jpkj.UtilFile;

/**
 *
 * @author sat
 */
public class NovaVenda extends javax.swing.JFrame {

    public static String number_format(String valor, int casas) {
        return number_format(Double.parseDouble(valor), casas);
    }

    public static String number_format(Double valor, int casas) {
        return number_format(valor, casas, null, null);
    }

    public static String number_format(String valor, int casas, String decimal, String milhar) {
        return number_format(Double.parseDouble(valor), casas, decimal, milhar);
    }

    public static String number_format(Double valor, int casas, final String decimal, final String milhar) {
        DecimalFormat df = new DecimalFormat();
        df.setCurrency(Currency.getInstance(Locale.US));
        df.setMinimumFractionDigits(casas);
        df.setDecimalFormatSymbols(new DecimalFormatSymbols() {

            @Override
            public char getDecimalSeparator() {
                if (decimal == null) {
                    return ',';
                } else {
                    if (decimal.isEmpty()) {
                        return '\0';
                    } else {
                        return decimal.charAt(0);
                    }
                }
            }

            @Override
            public char getGroupingSeparator() {
                if (milhar == null) {
                    return '.';
                } else {
                    if (milhar.isEmpty()) {
                        return '\0';
                    } else {
                        return milhar.charAt(0);
                    }
                }
            }
        });
        return df.format(valor);
    }

    /**
     * Creates new form NovaVenda
     */
    public NovaVenda() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Nova Venda");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        Bd.setSqlCombo(cloja, "select nome from lojas");
        Bd.setSqlCombo(produto, "select xprod from produtos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        cloja = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        xnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        xlgr = new javax.swing.JTextField();
        xbairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        xmun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        lblnro = new javax.swing.JLabel();
        nro = new javax.swing.JTextField();
        uf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        xcpl = new javax.swing.JTextField();
        cnpj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        produto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        qcom = new javax.swing.JTextField();
        vitem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        vdesc = new javax.swing.JTextField();
        cfop = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        produtos = new bean.DefaultTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tpag = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        vpag = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pagamentos = new bean.DefaultTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Loja");

        cloja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cloja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cloja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clojaItemStateChanged(evt);
            }
        });
        cloja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clojaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Logradouro");

        jLabel3.setText("Bairro");

        jLabel4.setText("Municipio");

        jLabel5.setText("CPF");

        lblnro.setText("Numero");

        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });

        jLabel7.setText("CNPJ");

        jLabel8.setText("UF");

        jLabel9.setText("Complemento");

        jLabel11.setText("Produto");

        produto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setText("QCOM");

        jLabel13.setText("Vitem");

        jLabel14.setText("VDesc");

        cfop.setText("5405");

        jLabel15.setText("CFOP");

        jLabel6.setText("Forma de Pagamento");

        tpag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01 - Dinheiro", "02 - Cheque", "03 - Crédito", "04 - Débito", "05 - Crédito em Loja", "99 - Outros" }));

        jLabel16.setText("Valor");

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Enviar Dados Venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(cloja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xlgr, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(xnome)
                            .addComponent(xbairro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblnro)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(nro, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(xmun, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnpj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(xcpl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(uf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vitem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qcom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cfop, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(produtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vpag, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cloja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(xnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(xlgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnro)
                    .addComponent(nro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xcpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(xbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xmun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel12)
                    .addComponent(qcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(vdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cfop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(vpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clojaActionPerformed

    }//GEN-LAST:event_clojaActionPerformed

    private void clojaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clojaItemStateChanged
        if (cloja.getSelectedItem() != null) {
            produtos.setSql("select * from venda_itens_tmp where loja='" + cloja.getSelectedItem() + "'");
            pagamentos.setSql("select * from venda_pagamentos_tmp where loja='" + cloja.getSelectedItem() + "'");
        }
    }//GEN-LAST:event_clojaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql = Bd.Insert("venda_itens_tmp", new String[]{
            "loja",
            "produto",
            "qcom",
            "vitem",
            "vdesc",
            "cfop"
        }, new String[]{
            cloja.getSelectedItem().toString(),
            produto.getSelectedItem().toString(),
            qcom.getText(),
            vitem.getText(),
            vdesc.getText(),
            cfop.getText()
        });
        Bd.exec(sql);
        produtos.update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String sql = Bd.Insert("venda_pagamentos_tmp", new String[]{
            "loja",
            "modo",
            "valor"
        }, new String[]{
            cloja.getSelectedItem().toString(),
            tpag.getSelectedItem().toString(),
            vpag.getText()
        });
        Bd.exec(sql);
        pagamentos.update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HashMap<String, String> loja = Bd.get("select * from lojas where nome='" + cloja.getSelectedItem().toString() + "'").get(0);
        HashMap<String, String> desenvolvedor = Bd.get("select * from desenvolvedores where id=?", new String[]{loja.get("desenvolvedores_id")}).get(0);
        String xml = "";
        xml += "<CFe>";
        xml += "<infCFe versaoDadosEnt=\"0.06\" >";
        xml += "<ide>";
        xml += "<CNPJ>" + desenvolvedor.get("cnpj") + "</CNPJ>";
        xml += "<signAC>" + loja.get("signac") + "</signAC>";
        xml += "<numeroCaixa>" + loja.get("numerocaixa") + "</numeroCaixa>";
        xml += "</ide>";
        xml += "<emit>";
        xml += "<CNPJ>" + loja.get("cnpj") + "</CNPJ>";
        xml += "<IE>" + loja.get("ie") + "</IE>";
        if (!loja.get("im").trim().isEmpty()) {
            xml += "<IM>" + loja.get("im") + "</IM>";
        }
        xml += "<indRatISSQN>" + loja.get("indratissqn") + "</indRatISSQN>";
        xml += "</emit>";
        if (!xnome.getText().isEmpty() || (!cpf.getText().isEmpty() || !cnpj.getText().isEmpty())) {
            xml += "<dest>";
            if (!cpf.getText().isEmpty()) {
                xml += "<CPF>" + cpf.getText().trim() + "</CPF>";
            }
            if (!cnpj.getText().isEmpty()) {
                xml += "<CNPJ>" + cnpj.getText().trim() + "</CNPJ>";
            }
            if (!xnome.getText().isEmpty()) {
                xml += "<xNome>" + xnome.getText().trim() + "</xNome>";
            }
            xml += "</dest>";
        } else {
            xml += "<dest>";
            xml += "<xNome>CLIENTE NAO INDENTIFICADO</xNome>";
            xml += "</dest>";
        }
        if (!xlgr.getText().trim().isEmpty()) {
            xml += "<entrega>";
            xml += "<xLgr>" + xlgr.getText() + "</xLgr>";
            xml += "<nro>" + nro.getText() + "</nro>";
            if (!xcpl.getText().isEmpty()) {
                xml += "<xCpl>" + xcpl.getText() + "</xCpl>";
            }
            xml += "<xBairro>" + xbairro.getText() + "</xBairro>";
            xml += "<xMun>" + xmun.getText() + "</xMun>";
            xml += "<UF>" + uf.getText() + "</UF>";
            xml += "</entrega>";
        } else {
            //xml += "<entrega />";
            Msg.show("Um local de entrega precisa ser determinado");
            return;
        }
        int nItem = 0;
        for (HashMap<String, String> item : Bd.get("select * from venda_itens_tmp where loja='" + cloja.getSelectedItem().toString() + "'")) {
            HashMap<String, String> produto = Bd.get("select * from produtos where xprod=?", new String[]{item.get("produto")}).get(0);
            xml += "<det nItem=\"" + nItem + "\">";
            xml += "<prod>";
            xml += "<cProd>" + produto.get("cprod") + "</cProd>";
            xml += "<cEAN>" + produto.get("cean") + "</cEAN>";
            xml += "<xProd>" + produto.get("xprod") + "</xProd>";
            xml += "<NCM>" + produto.get("ncm") + "</NCM>";
            xml += "<CFOP>" + item.get("cfop") + "</CFOP>";
            xml += "<uCom>" + produto.get("ucom") + "</uCom>";
            xml += "<qCom>" + number_format(item.get("qcom"), 4, ".", "") + "</qCom>";
            xml += "<vUnCom>" + number_format(item.get("vitem"), 2, ".", "") + "</vUnCom>";
            xml += "<indRegra>" + produto.get("indregra") + "</indRegra>";
            if (Double.parseDouble(item.get("vdesc")) > 0) {
                xml += "<vDesc>" + number_format(item.get("vdesc"), 2, ".", "") + "</vDesc>";
            }
            xml += "</prod>";
            xml += "<imposto>";
            xml += "<vItem12741>" + number_format(item.get("vitem"), 2, ".", "") + "</vItem12741>";
            xml += "<ICMS>";
            xml += "<ICMS" + produto.get("icms_cst") + ">";
            xml += "<Orig>" + produto.get("orig") + "</Orig>";
            xml += "<CST>" + produto.get("icms_cst") + "</CST>";
            xml += "<pICMS>" + number_format(produto.get("icms_porcentagem"), 4, ".", "") + "</pICMS>";
            xml += "</ICMS" + produto.get("icms_cst") + ">";
            xml += "</ICMS>";
            xml += "<PIS>";
            if (Double.parseDouble(produto.get("pis_porcentagem")) > 0) {
                xml += "<PISAliq>";
                xml += "<CST>" + produto.get("pis_cst") + "</CST>";
                xml += "<vBC>" + number_format(item.get("vitem"), 2, ".", "") + "</vBC>";
                xml += "<pPIS>" + number_format(produto.get("pis_porcentagem"), 4, ".", "") + "</pPIS>";
                xml += "</PISAliq>";
            } else {
                xml += "<PISNT>";
                xml += "<CST>" + produto.get("pis_cst") + "</CST>";
                xml += "</PISNT>";
            }
            xml += "</PIS>";
            xml += "<COFINS>";
            if (Double.parseDouble(produto.get("cofins_porcentagem")) > 0) {
                xml += "<COFINSAliq>";
                xml += "<CST>" + produto.get("cofins_cst") + "</CST>";
                xml += "<vBC>" + number_format(item.get("vitem"), 2, ".", "") + "</vBC>";
                xml += "<pCOFINS>" + number_format(produto.get("cofins_porcentagem"), 4, ".", "") + "</pCOFINS>";
                xml += "</COFINSAliq>";
            } else {
                xml += "<COFINSNT>";
                xml += "<CST>" + produto.get("cofins_cst") + "</CST>";
                xml += "</COFINSNT>";
            }
            xml += "</COFINS>";
            xml += "</imposto>";
            xml += "</det>";
            nItem++;
        }
        xml += "<total></total>";
        xml += "<pgto>";
        for (HashMap<String, String> pagamento : Bd.get("select * from venda_pagamentos_tmp where loja='" + cloja.getSelectedItem().toString() + "'")) {
            String modo = pagamento.get("modo").split(Pattern.quote("-"))[0].trim();
            xml += "<MP>";
            xml += "<cMP>" + modo + "</cMP>";
            xml += "<vMP>" + number_format(pagamento.get("valor"), 2, ".", "") + "</vMP>";
            xml += "</MP>";
        }
        xml += "</pgto>";
        xml += "</infCFe>";
        xml += "</CFe>";
//        UtilFile.write("ultimaVenda.xml", xml);
        String retorno = DLL.EnviarDadosVenda(xml);
        RetornoVenda ret = new RetornoVenda(retorno, "0");
        if (ret.erro) {
            Msg.show("Erro ao emitir \n" + ret.getMensagem() + " | " + ret.getMensagemSEFAZ());
            return;
        }
        cupom.Driver.print(ret.xml);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cfop;
    private javax.swing.JComboBox cloja;
    private javax.swing.JTextField cnpj;
    private javax.swing.JTextField cpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblnro;
    private javax.swing.JTextField nro;
    private bean.DefaultTable pagamentos;
    private javax.swing.JComboBox produto;
    private bean.DefaultTable produtos;
    private javax.swing.JTextField qcom;
    private javax.swing.JComboBox tpag;
    private javax.swing.JTextField uf;
    private javax.swing.JTextField vdesc;
    private javax.swing.JTextField vitem;
    private javax.swing.JTextField vpag;
    private javax.swing.JTextField xbairro;
    private javax.swing.JTextField xcpl;
    private javax.swing.JTextField xlgr;
    private javax.swing.JTextField xmun;
    private javax.swing.JTextField xnome;
    // End of variables declaration//GEN-END:variables
}
